FORMAT: 1A
HOST: http://api.domain.com/

# QR-CODE Micro service 

Micro service for generating QR codes

## QR Code [/qr/create{?size,data,format,color,bgcolor}]

### create  [GET]

+ Parameters

    + size (number)
        Minimum value:
        10 px
        Maximal value:
        1000 (if format=png|gif|jpeg|jpg),
        1000000 (if format=svg|eps)

    + data (string) 
        
        The text to store within the QR code (URL encoded, PHP programmers may use urlencode()).
        
    + format (enum[string], optional)

        Set file format, default PNG.

        + Members
            + `png`
            + `jpeg`
            + `svg`
            + `pdf`  
            
    + color (string, optional)
        
        Set Text color  as RGB value, default #000000.
            
    + bgcolor (string, optional)
        
        Set backgroud color as RGB value, default #ffffff. 
        
        
+ Response 200 (image/png)

+ Response 400